# Generated by Django 5.0.6 on 2024-06-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
